stages:
  - build
  - test

build-backend:
  stage: build
  image: python:3.11
  script:
    - apt-get update
    - apt-get install -y python3-pip
    - python3 -m venv venv
    - source venv/bin/activate
    - cd backend
    - pip install -r requirements.txt

test-backend:
  stage: test
  image: python:3.11
  script:
    - cd backend
    - pip install pytest
    - pytest
