stages:
  - build
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - backend/venv/
    - backend/__pycache__/

build-backend:
  stage: build
  image: python:3.11
  script:
    - apt-get update
    - apt-get install -y python3-pip
    - python3 -m venv venv
    - source venv/bin/activate
    - cd backend
    - pip install -r requirements.txt
  artifacts:
  paths:
    - backend/venv
  expire_in: 1 week

test-backend:
  stage: test
  image: python:3.11
  script:
    - cd backend
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - pytest
  artifacts:
    paths:
      - backend/venv
    expire_in: 1 week


