version: '3.8'
services:
  db_mysql:
    image: mysql/mysql-server:latest
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: team24db
      MYSQL_DATABASE: team24db
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db-mysql:/var/lib/mysql
    ports: 
      - "53376:3306"

volumes:
  db-mysql:
